name: GitHub Actions Demo
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "üñ•Ô∏è The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Check how secrets work
        run: echo "The secret is `${{ secrets.SUPER_SPECIAL_SECRET }}`"
      - run: echo "üçè This job's status is ${{ job.status }}."
  test_composite_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - uses: ./.github/actions/action_gradle_run
        with:
          gradle_task: "tasks --all"
          gradle_workDir: 'testPath'
          gradle_flags: "-PglobalidMavenUsername2=${{ github.actor }} -PglobalidMavenPassword2=${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
  test_composite_action2:
    runs-on: ubuntu-latest
    steps:
      - uses: ribafish/action-gradle-run@v6
        with:
          gradle_task: "tasks --all"
          gradle_workDir: 'testPath'
          gradle_flags: "-PglobalidMavenUsername2=${{ github.actor }} -PglobalidMavenPassword2=${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          maven_username: ${{ github.actor }}
          maven_password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  test_composite_action3:
    runs-on: ubuntu-latest
    steps:
      - uses: ribafish/action-gradle-run@main
        with:
          gradle_task: "tasks --all"
          gradle_workDir: 'testPath'
          gradle_flags: "-PglobalidMavenUsername2=${{ github.actor }} -PglobalidMavenPassword2=${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          maven_username: ${{ github.actor }}
          maven_password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          condition: WAZZAAAPPPP
